name: Islam Elgendy
description: Personal website
menu:
  - page: About
    url: /about
  - page: Papers
    url: /papers
    links:
      - title: Working papers
        url: "#working-papers"
      - title: Published papers
        url: "#published-papers"
  - page: Research Projects
    url: /research
    # links:
    #   - title: "Diversity in Test Case Prioritization"
    #     url: "#project-one"
    #   - title: "Targeting Stubborn Mutants"
    #     url: "#project-two"
  - page: Curriculum Vitae
    url: /cv
    links:
      - title: Experience
        url: "#experience"
      - title: Education
        url: "#education"
      - title: Miscellaneous
        url: "#miscellaneous"
  - page: Teaching
    url: /teaching
  - page: Media
    url: /media
  - page: Accolades
    url: /accolades
menu_external:
  - title: University Profile
    url: "https://www.sheffield.ac.uk/cs/people/academic/islam-elgendy"
  - title: Google Scholar
    url: "https://scholar.google.co.uk/citations?user=0TgqOAUAAAAJ&hl=en&oi=sra"
  - title: Research Gate
    url: "https://www.researchgate.net/profile/Islam-Elgendy-2"
  - title: LinkedIn
    url: "https://no.linkedin.com/in/islam-elgendy-484664238"
mathjax: false
markdown: kramdown
encoding: utf-8
baseurl: "islamelgendy.github.io"
locale: en_GB
